export default [
    {
        level: 1,
        scoreNeeded: 0,
        spawnRate: 800,
        dropSpeed: 550,
        bombSpawnChance: 0,
        lifeSpawnChance: 0,
    },
    {
        level: 2,
        scoreNeeded: 5,
        spawnRate: 800,
        dropSpeed: 650,
        bombSpawnChance: 0,
        lifeSpawnChance: 0,
    },
    {
        level: 3,
        scoreNeeded: 10,
        spawnRate: 750,
        dropSpeed: 700,
        bombSpawnChance: 20,
        lifeSpawnChance: 0,
    },
    {
        level: 4,
        scoreNeeded: 20,
        spawnRate: 700,
        dropSpeed: 800,
        bombSpawnChance: 20,
        lifeSpawnChance: 0,
    },
    {
        level: 5,
        scoreNeeded: 35,
        spawnRate: 600,
        dropSpeed: 900,
        bombSpawnChance: 25,
        lifeSpawnChance: 0,
    },
    {
        level: 6,
        scoreNeeded: 50,
        spawnRate: 500,
        dropSpeed: 950,
        bombSpawnChance: 25,
        lifeSpawnChance: 0,
    },
    {
        level: 7,
        scoreNeeded: 70,
        spawnRate: 450,
        dropSpeed: 1000,
        bombSpawnChance: 30,
        lifeSpawnChance: 0,
    },
    {
        level: 8,
        scoreNeeded: 90,
        spawnRate: 400,
        dropSpeed: 1100,
        bombSpawnChance: 32,
        lifeSpawnChance: 5,
    },
    {
        level: 9,
        scoreNeeded: 110,
        spawnRate: 300,
        dropSpeed: 1200,
        bombSpawnChance: 32,
        lifeSpawnChance: 4,
    },
    {
        level: 10,
        scoreNeeded: 130,
        spawnRate: 200,
        dropSpeed: 1300,
        bombSpawnChance: 35,
        lifeSpawnChance: 3,
    },
    {
        level: "Master",
        scoreNeeded: 160,
        spawnRate: 140,
        dropSpeed: 1350,
        bombSpawnChance: 40,
        lifeSpawnChance: 2,
    },
    {
        level: "Legendary",
        scoreNeeded: 250,
        spawnRate: 100,
        dropSpeed: 1400,
        bombSpawnChance: 45,
        lifeSpawnChance: 2,
    },
    {
        level: "God",
        scoreNeeded: 400,
        spawnRate: 75,
        dropSpeed: 1450,
        bombSpawnChance: 50,
        lifeSpawnChance: 2,
    },
    {
        level: "MAXIMUM OVERLOAD!!!",
        scoreNeeded: 800,
        spawnRate: 50,
        dropSpeed: 1500,
        bombSpawnChance: 60,
        lifeSpawnChance: 2,
    },
]